import Head from 'next/head'
import Header from '../components/header'
import NavBar from '../components/navBar'
import Results from '../components/Results'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Acer Overlord</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header/>


      {/* Nav Bar */}
      <NavBar/>

      {/* Results */}
      <Results/>
    </div>
  )
}